### ISSUE TITLE
it errors after giving it my token

### ISSUE THREAD

**Issue by Therealloli101** [VissarionSB/Vissarion#4]
Status          <~ Connecting...
Account         <~ YoYmonokal#5776
Prefix          <~ v!

Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002395330D900>
Traceback (most recent call last):
  File "C:\Users\lemmi\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\lemmi\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\lemmi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\lemmi\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by archivine** [comment]
Please ensure that your token is valid and that you're using the right discord package - discord.py-self.

**Comment by archivine** [comment]
closed for inactivity
